### ISSUE TITLE
Please support ISO dates

### ISSUE THREAD

**Issue by tbm** [Destaq/language-learning-dashboard#1]
The README says:

> note dates have to be at the top in the format MM/DD/YY

Can you please support at least ISO 8601 dates, i.e. YYYY-MM-DD

https://en.wikipedia.org/wiki/ISO_8601

**Comment by Destaq** [comment]
This format was actually supported by `dateutil` out of the box, I was just unaware of this. The documentation has been updated to reflect the fact that it can be used.

**Comment by tbm** [comment]
Thanks!
