### ISSUE TITLE
Vocabulary heat map?

### ISSUE THREAD

**Issue by GrimPixel** [Destaq/language-learning-dashboard#3]
I have another idea: [https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Ideas-about-language-learning#Vocabulary_heat_map](vocabulary heat map), where there could be words or phrases in grids and the user's familiarity them can be visualised.

**Comment by Destaq** [comment]
Like I shared earlier, the main purpose of this app is just to simply track time spent language learning and general progress over time. The site you have been linking to is interesting, but I'm afraid that I and this project are not the right person/tool for you to approach.

**Comment by Destaq** [comment]
The project is more or less completed as it stands.
