### ISSUE TITLE
Fork Disclosure - Desktop App

### ISSUE THREAD

**Issue by tcardlab** [Destaq/language-learning-dashboard#5]
This isn't really an issue, nor directly related to anything you are doing. I just wanted to disclose that I used this repo in a minor tech exploration project.

The [forked](https://github.com/tcardlab/language-learning-dashboard) repo essentially makes it a self-contained desktop app.
I primarily did this as a means to compare Tauri vs Electron when dealing with a sidecar and/nix client-server. I also added FlaskWebGUI because it was easy. I made no considerations toward updates, migrations, nor imports/exports.

I have the 3 different releases [here](https://github.com/tcardlab/language-learning-dashboard/releases).

Best of luck on your new project LingoTrack!

**Comment by Destaq** [comment]
Hi there, thanks for letting me know! I'm glad that my project was useful for your desktop app exploration. Any reason you picked it in particular?

Anyways, all's good on your front. Just please don't sell copies of the binaries etc.

**Comment by tcardlab** [comment]
> Any reason you picked it in particular?

Mostly coincidence, someone mentioned it while I was looking for a way to test Tauri sidecars/client-servers. Saw it was flask and figured I could slam it out pretty quickly in my free time.
